apiVersion: v1
kind: Service
metadata:
  labels:
    app: dailyfeed-timeline-svc
  name: dailyfeed-timeline-svc
  namespace: dailyfeed
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dailyfeed-timeline-svc
  type: ClusterIP
status:
  loadBalancer: {}
