apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-09-06T03:52:05Z"
  generateName: dailyfeed-timeline-5b56f54f7c-
  generation: 1
  labels:
    app: dailyfeed-timeline
    pod-template-hash: 5b56f54f7c
  name: dailyfeed-timeline-5b56f54f7c-n5jdm
  namespace: dailyfeed
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: dailyfeed-timeline-5b56f54f7c
    uid: 7ae6b04b-89ca-4710-9fc9-0d657f5ffdb5
  resourceVersion: "129597"
  uid: 3ec8b3f9-077f-4906-82ba-3baaa10ca34d
spec:
  containers:
  - env:
    - name: SPRING_PROFILES_ACTIVE
      value: local
    - name: MEMBER_SERVICE_URL
      value: http://dailyfeed-member-svc.dailyfeed.svc.cluster.local
    - name: SEARCH_SERVICE_URL
      value: http://dailyfeed-search-svc.dailyfeed.svc.cluster.local
    - name: CONTENT_SERVICE_URL
      value: http://dailyfeed-content-svc.dailyfeed.svc.cluster.local
    envFrom:
    - configMapRef:
        name: kafka-config
    - secretRef:
        name: kafka-secret
    - configMapRef:
        name: redis-config
    - configMapRef:
        name: mysql-config
    - secretRef:
        name: mysql-secret
    - configMapRef:
        name: mongodb-config
    - secretRef:
        name: mongodb-secret
    image: alpha300uk/dailyfeed-timeline-svc:0.0.1
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sh
          - -c
          - sleep 10
    livenessProbe:
      failureThreshold: 7
      httpGet:
        path: /healthcheck/live
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 1
    name: dailyfeed-timeline
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthcheck/ready
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 500Mi
    startupProbe:
      failureThreshold: 3
      httpGet:
        path: /healthcheck/startup
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-z5gfw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: istio-cluster-worker
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-z5gfw
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-09-06T03:52:06Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-09-06T03:52:05Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-09-06T03:52:05Z"
    message: 'containers with unready status: [dailyfeed-timeline]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-09-06T03:52:05Z"
    message: 'containers with unready status: [dailyfeed-timeline]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-09-06T03:52:05Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 500m
      memory: 500Mi
    containerID: containerd://a03a346b5e4cfcfaf223e5869becf09fda8b811a8a26936d2413d1381de53f71
    image: docker.io/alpha300uk/dailyfeed-timeline-svc:0.0.1
    imageID: docker.io/alpha300uk/dailyfeed-timeline-svc@sha256:ad806367bd272d9eec1eff07bd8ebcdb43c5496d1c9a09363a3aff4781e0dfd0
    lastState:
      terminated:
        containerID: containerd://a03a346b5e4cfcfaf223e5869becf09fda8b811a8a26936d2413d1381de53f71
        exitCode: 1
        finishedAt: "2025-09-06T03:54:35Z"
        reason: Error
        startedAt: "2025-09-06T03:54:23Z"
    name: dailyfeed-timeline
    ready: false
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 500Mi
    restartCount: 4
    started: false
    state:
      waiting:
        message: back-off 1m20s restarting failed container=dailyfeed-timeline pod=dailyfeed-timeline-5b56f54f7c-n5jdm_dailyfeed(3ec8b3f9-077f-4906-82ba-3baaa10ca34d)
        reason: CrashLoopBackOff
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 1000
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-z5gfw
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.97.2
  hostIPs:
  - ip: 192.168.97.2
  phase: Running
  podIP: 10.244.1.68
  podIPs:
  - ip: 10.244.1.68
  qosClass: Burstable
  startTime: "2025-09-06T03:52:05Z"
